### ISSUE TITLE
Could you tell me how to get intrinsics of TOF camera of honor view 20?

### ISSUE THREAD

**Issue by dejianwei** [remmel/image-processing-js#1]
```
export const HONOR20VIEW_DEPTH_INTRINSICS = {  //default my Honor 20 View intrinsics
  w: 240, //x
  h: 180, //y
  fx: 178.824,
  fy: 179.291,
  cx: 119.819,
  cy: 89.13,
}
```

**Comment by remmel** [comment]
I dont remember, but I probably get thoses data from AREngine https://developer.huawei.com/consumer/en/hms/huawei-arengine/?ha_source=hms1

**Comment by dejianwei** [comment]
Thank you very much, it is quiet helpful.

**Comment by remmel** [comment]
Hi,
Now I remember: thoses data are coming from `arFrame.getCamera().getCameraImageIntrinsics()`, thoses seems to be factory values (fixed)
Java code and values: https://github.com/remmel/recorder-3d/blob/388592f96a36f0ef764774d9daa2dcf6b6620bf4/Recorder3D/src/main/java/com/remmel/recorder3d/recorder/RecorderRenderManager.java#L330

AREngine doc: https://developer.huawei.com/consumer/en/doc/development/graphics-References/camera_intrinsics-0000001051140882
